### ISSUE TITLE
Connect to libxposed service in hooked app

### ISSUE THREAD

**Issue by neervanbiqs** [libxposed/service#9] opened 2024-09-28 12:11 UTC
Is it possible to connect to the libxposed service inside the onPackageLoaded method? My module reads variables from the sharedprefs and as a result of hooking some methods, some variables in sharedprefs need to be rewritten, but sharedprefs inside onPackageLoaded are opened only for reading. The same applies to files. The module needs to be able to open files not only for reading, but also for writing. Is this possible using the service? Or is connecting to the service only possible when the module is launched itself? 
If not, are there any workarounds?

**Comment by vvb2060** [comment] 2024-09-28 12:32
Duplicate of https://github.com/libxposed/api/issues/15

**Closed as not planned by vvb2060** 2024-09-28 12:32 UTC
